adopted-ember-addons/emberx-select

- addon/components/x-option.js
- addon/components/x-select.js
> some fixes + cleanup

- Brocfile.js
- addon/components/x-option.js
- addon/components/x-select.js
- bower.json
- package.json
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
I think I nailed it! Example in the dummy app.
I'm not very familiar with mocha. Maybe you could write the needed tests.
Otherwise I can certainly look into it later.
This PR includes #6.
> Add multiple selection feature

- README.md
- addon/helpers/register-select-helper.js
- app/helpers/register-select-helper.js
https://github.com/thefrontside/emberx-select/issues/13
Adds the `select` helper to deal with integration level tests.
Closes #13.
> Introduce `registerSelectHelper`

- app/templates/components/x-select.hbs
Was firing a deprecation warning with Ember 1.13. Simple fix use `each as` rather than `each in`
> Use block params

- addon/components/x-option.js
- addon/components/x-select.js
- app/templates/components/x-select.hbs
- bower.json
- package.json
- tests/.jshintrc
- tests/acceptance/x-select-multiple-blockless-test.js
- tests/acceptance/x-select-multiple-test.js
- tests/acceptance/x-select-single-blockless-option-value-test.js
- tests/acceptance/x-select-single-blockless-test.js
- tests/acceptance/x-select-single-test.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/controllers/blockless-multiple.js
- tests/dummy/app/controllers/blockless-single.js
- tests/dummy/app/controllers/multiple.js
- tests/dummy/app/controllers/single.js
- tests/dummy/app/templates/blockless-multiple.hbs
- tests/dummy/app/templates/blockless-single.hbs
- tests/dummy/app/templates/multiple.hbs
- tests/helpers/get-component-by-id.js
- tests/helpers/start-app.js
This still doesn't have all the tests passing.
1. test against Ember 1.13.2
1. change `{{#each foo in foos}}` to `{{#each foos as |foo|}}`
1. introduce `getComponentById` helper that uses `app.__container__.lookup('-view-registry:main')` since Ember no longer exposes `Ember.View.views`
1. don't call `set` in `didInsertElemenent` because that can cause performance problems in Glimmer; instead, defer the `set` to the `afterRender` queue
1. eliminate use of `Ember.ObjectController` in tests
1. use the `change` handler that `Ember.Component`s come with instead of adding a handler in `didInsertElement` via `this.$.on('change')`
1. remove observer on `content.@each` that was writing changes back upstream and sending actions. In Glimmer, the component will get rerendered automatically from …
> Clean up some Glimmer deprecations

- .editorconfig
- .travis.yml
- .watchmanconfig
- Brocfile.js
- addon/components/x-option.js
- addon/components/x-select.js
- bower.json
- config/ember-try.js
- package.json
- testem.json
- tests/acceptance/x-select-multiple-blockless-test.js
- tests/acceptance/x-select-multiple-test.js
- tests/acceptance/x-select-single-blockless-option-value-test.js
- tests/acceptance/x-select-single-blockless-test.js
- tests/acceptance/x-select-single-test.js
- tests/dummy/app/app.js
- tests/dummy/config/environment.js
- tests/dummy/public/crossdomain.xml
- tests/dummy/public/robots.txt
I removed prototype extensions that snuck into the addon, updated to the latest ember-cli, and added a demo page.
> Update Ember-CLI / Remove prototype extensions

- .travis.yml
- bower.json
- tests/acceptance/x-select-zany-embedded-html-test.js
- tests/dummy/app/controllers/zany-embedded-html.js
- tests/dummy/app/router.js
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/zany-embedded-html.hbs
In order to fetch the parentView for an element reliably, we depend on a
bugfix that only came available in Ember v1.13.4
https://github.com/emberjs/ember.js/pull/11266
This also adds a test case that was breaking in 1.13.{0-3}
resolves #44
> bump ember dependency for parentView bugfix.

- addon/components/x-option.js
According to the [ember 1.13.0][ember] release notes, `didRender` will
be called after the element is inserted.
This makes manually scheduling code to the `afterRender` queue obsolete.
```
DEPRECATION: A property of <my-app@view:-outlet::ember547> was modified
inside the `didInsertElement` hook. You should never change properties
on components, services or models during `didInsertElement` because
it causes significant performance degradation.
```
[ember]: http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html
> Use `didRender` in `x-option`

- addon/components/x-select.js
It used to be with multiselects you would edit the value array in place
as you intereacted with the select component. This caused problems
especially when have collections such as async ember data
relationships.
Now we always create a new array for every single selection.
> Make array values immuatable

- addon/components/x-option.js
This fixes #66. I ended up having to move the way we register x-option
with it's parent component into an ember after render run loop.
> Remove depercation caused changing data in didRender

- addon/components/x-option.js
Just a simple hook rename didRender() -> didInsertElement()
See #70
> Schedule x-option registration in didInsertElement() hook instead of didRender()

- README.md
It's confusing that it's different in different readmes. It should just
be a single block that you can see everywhere.... even if that means including the link to a repository within its own readme
> Standardize on the emberx directory.

- tests/dummy/app/controllers/multiple.js
- tests/dummy/app/templates/multiple.hbs
- tests/dummy/config/environment.js
The demo was relying on two way data binding to update its values. Now we
use the propery is being set by the action.
Also switched to `hash` location so the gh-pages demo works correctly.
> Fixes demo for multiple

- addon/components/x-option.js
- tests/unit/components/x-option-test.js
This is a dupe of https://github.com/thefrontside/emberx-select/pull/75 but with a test (and minor change in syntax).
> Fix issue with unregisterOption (with Test) 

- addon/components/x-select.js
- bower.json
- package.json
- tests/acceptance/shared/attr-test.js
This is to remove the leftover properties in x-select that were there
for x-select-blockless. We've since moved blockless to its own repo.
I also did a little clean up and fixed a jshint test.
> Remove dead properties leftover from x-select-blockless

- addon/components/x-select.js
- tests/acceptance/default-values-test.js
- tests/acceptance/x-select-multiple-test.js
- tests/dummy/app/controllers/default-value.js
- tests/dummy/app/mixins/cars.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/default-value.js
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/default-value.hbs
Provides support for #81 by allowing the implementer to specify `selected=true` property on an x-option component to set a default value for the selection. 
Implementers can use this update to default to the first item in a dynamic list by taking advantage of the index block param for the each helper.  This solution is provided as a compromise to allow implementers to opt in to default selection behavior. Further improvements may be made at a later date.
```
{{#x-select value=(mut make) action=(action "setMake") class="spec-car-make"}}
{{#x-option value=ford}}Ford{{/x-option}}
{{#x-option value=honda selected=true}}Honda{{/x-option}}
{{#x-option value=toyota}}Toyota{{/x-option}}
<option>Not Selected</option>
{{/x-select}}
```
Will default to option two (Honda) if no explicit value for …
> Update register code to set default option

- addon/components/x-select.js
- bower.json
- package.json
- tests/acceptance/ember-data-test.js
- tests/dummy/app/controllers/ember-data.js
- tests/dummy/app/models/person.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/ember-data.js
- tests/dummy/app/styles/app.css
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/ember-data.hbs
Related to #94 
We don't want to set the value of the component if we're destroying the component. This is what's happening in #94. 
TODOs:
> Don't update value if tearing component down

- README.md
> Fix the README description

- addon/components/x-select.js
If you have attributes like `multiple` or `disabled` set on a `<select>`
at all it will think it's true. Even if you set `disabled="false"` it
will still disable selects.
By intializing the defaults to null it won't apply the attribute to the select
> Intialize defaults to `null` rather than false

- addon/components/x-select.js
Don't update the values if the component is being destroyed or is destroyed. This cropped up as a problem when the x-select was inside a liquid-if.
> check state before updating value

- config/ember-try.js
- package.json
Read more here: http://codeallday.com/blog/new-easier-ember-try-config-for-most-addons/
> Use versionCompatibility config from ember-try

- README.md
- addon/components/x-select.js
- tests/integration/components/two-way-data-binding-test.js
Now you can pass an attribute called `hasTwoWay` and set it to false to
disable two way data binding. Should close #121.
> Add the ability to disable two way data binding

- README.md
- addon/components/x-select.js
- tests/integration/components/two-way-data-binding-test.js
This separates the `read` operation from the `write` operation which turns out to be a very handy thing. It turns out that reading a multi select value and a single select value is the only difference.
So upon an update, we read the next value (which depends on the selection type) and then, regardless of whethere it is multi or not, we `set` the value if it is a two-way binding.
fixes #131, closes #129
> fix the one-way binding attribute.

- addon/components/x-select.js
- tests/integration/components/two-way-data-binding-test.js
This was a small fix to make sure when `one-way` is set to `true` we fire the action on init rather than try to bind the data. 
This needs a 2nd pair of eyes, I'd like @cafreeman see if this fixes his issues using this with `x-form`.
> Fire action when one-way is true and no default value provided

- addon/components/x-select.js
- tests/acceptance/x-select-multiple-test.js
- tests/acceptance/x-select-single-test.js
- tests/dummy/app/controllers/default-value.js
- tests/dummy/app/controllers/single.js
- tests/dummy/app/templates/default-value.hbs
RIP in peace 2015-2016. Probably won't be missed tho.
> Kill two way data binding

- README.md
- blueprints/emberx-select/index.js
- test-support/helpers/register-select-helper.js
- test-support/helpers/x-select.js
- tests/integration/components/two-way-data-binding-test.js
- tests/test-helper.js
Ready for review.
This makes the `select` helper more robust. First and foremost you can now import the select helper directly:
```js
import { select } from 'yourappname/tests/helpers/x-select';
```
Also you can pass a jquery object to the helper instead of just a string. This is useful in component integration tests: `select(this.$('.x-select'), 'option')`. The options are now not case sensitive. 
- Renamed the file name to `x-select`
> Extract select test helper to an exported function

- README.md
- addon/components/x-option.js
- bower.json
- ember-cli-build.js
- package.json
- tests/integration/components/x-select-actions-test.js
The goal for this is to close #136. We would like to fire an action any time an option is disabled. With that action we send the disabled value (true or false) & the value of that option. 
@jameshoward I would love to get your feedback on this.
> Fire action on x-option when disabled

- addon/components/x-select.js
In Ember, `.extend` is shorthand for defining properties on the
prototype. Anything put on the prototype will be shared by all of its
instances.
For example:
```javascript
const Test = Ember.Object.extend({
results: []
});
const test1 = Test.create();
const test2 = Test.create();
test1.get('results').push(1);
test1.get('results'); // [1]
test2.get('results'); // [1]
```
`x-select` instances were sharing `options` between instances. While
this didn't manifest itself in any user-facing bugs, it will in the
future in subtle ways.
This PR changes `options` to be a computed property so that each
instance gets its own `options` array.
> don't share `options` arrays between x-select instances

- addon/components/x-select.js
In Ember, willDestroyElement is a cleanup or destructor hook. This means
when it is overridden, `this._super` should be called last to avoid
collisions with Ember's cleanup code.
> call willDestroyElement's this._super last

- addon/components/x-select.js
tl;dr we can call the `_setDefaultValues()` function only once when rendering
a bunch of components or destroying a bunch of components.
If you have a list with a large amount of selects (~ 40 in our app),
the `_setDefaultValues` function can get pretty expensive as it has to query
the DOM every time. This gets slowly more costly to query as registering
40 `<option>` elements calls the `_setDefaultValues` function 40 times.
In addition to the 40 times the function is called, the number of
elements slowly grows as well. This ends up being n^2\2. After this PR, it's just 1 time.
> coalesce registering and unregistering options

- addon/components/x-select.js
This commit has 2 goals:
1) A small refactoring of the getValue method to split out the
multiple/single value cases.
2) Decrease the number of elements `_getValue` searches through if
possible. `Array.prototype.find` stops iterating on the array when the
callback returns truthy. `options` is an `Ember.A` which means it should
polyfill the `Array.prototype.find` method.
Say you have an array like:
```javascript
const values = [1, 2, 3];
```
If we're looking for the value `2`, we only want to search the array two
times, because the number 2 is found on the second iteration.
This reduces the amount of work we have to do on larger arrays because
we can bail if the element is found early. While this doesn't matter
much on an array of 5, it can matter more with bigger arrays especially
since …
> reduce number of components searched

- addon/components/x-select.js
- tests/acceptance/default-values-test.js
- tests/dummy/app/controllers/default-value.js
@Robdel12 I'm not sure the impetus for changing the conditional in #140 [here](https://github.com/thefrontside/emberx-select/commit/fc7fdba978c114182937919d63dfd5d1e7f0a1ae#diff-61de3d9cb98ddeb2c88de3a2d3b03af3R131) but I found this to cause default values to not bind correctly if the property was `undefined`.  
For the test I co-opted a piece of the existing acceptance test that was not actually being tested.
/cc @fivetanley
> Fix bug where undefined initial values were changed to null

- addon/components/x-select.js
This restores a guard that used to exist around trying to set a default value while the component is being torn down.  The changes from #152 made this necessary again as `this.get('value')` is `null` during teardown which was causing bad things to happen.
> guard against __setDefaultValues being called during teardown

- config/ember-try.js
- index.js
- package.json
In the near future (ember-cli@2.11) Ember itself will be obtained from the `ember-source` npm package (instead of via Bower). 
This PR paves the way for additional testing (current emberx-select errors when Ember is not present via Bower), and adds ember-source to an ember-try scenario.
> Allow ember-source npm package to work.

- addon/components/x-select.js
This is a slight change to #169 which adds a UA sniff before doing some fake value setting to avoid an Edge bug. Here's #169's PR description: 
> This is a hackish compensation for a [bug in Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8794503/). I don’t think it’s necessarily something you’d even want in your codebase because it’s so unsightly, but I’m submitting it to get your feedback. (Also it’s branched off `v2.2.2` because I haven’t yet converted to contextual components.)
> Without this, a select with the required flag is marked as invalid until you change the value. You can change the value yourself and then change it back to the default, but even that workaround fails if the select only has one value.
> I don’t really feel like this is an acceptable …
> UA sniff for bad MS Edge bug (required selects must change value to be valid)

- addon/components/x-select.js
This is a slight change to #169 which adds a UA sniff before doing some fake value setting to avoid an Edge bug. Here's #169's PR description: 
> This is a hackish compensation for a [bug in Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8794503/). I don’t think it’s necessarily something you’d even want in your codebase because it’s so unsightly, but I’m submitting it to get your feedback. (Also it’s branched off `v2.2.2` because I haven’t yet converted to contextual components.)
> Without this, a select with the required flag is marked as invalid until you change the value. You can change the value yourself and then change it back to the default, but even that workaround fails if the select only has one value.
> I don’t really feel like this is an acceptable …
> UA sniff for bad MS Edge bug (required selects must change value to be valid --glimmer PR)

- addon/components/x-select.js
From the original commit: 
> There was an issue when a computed property was changed... The selected property on options fired multiple times and threw a series of deprecation warnings. See #158
> Thanks to @bmass02
Back porting this to v2.2.3
> Fixed Bug with computed properties (to v2.2.3)

- .gitignore
- .travis.yml
- bower.json
- config/ember-try.js
- package.json
- tests/dummy/config/environment.js
- tests/helpers/start-app.js
- tests/index.html
- yarn.lock
This upgrades ember-cli & fixes the odd CI deploy fails.
> Upgrade ember-cli

- Changelog.md
I noticed this when I tried to upgrade to 2.2.3 in order to get the fix for the deprecation fixed in #166. The Changelog says that fix was included in 2.2.3, but it's actually in 3.0.0.
> Correct 2.2.3 Changelog.md entry

- README.md
Since 1.13, the preferred way of dispatching actions is with closures, so our readme should reflect that.
> don't use deprecated action dispatch in example

- addon/components/x-option.js
Gotta pass `this` when using `.apply`.
> fix this._super call in x-option

- .circleci/config.yml
- .eslintrc.js
- .npmignore
- .travis.yml
- CNAME
- addon/components/x-option.js
- addon/components/x-select.js
- config/ember-try.js
- config/environment.js
- ember-cli-build.js
- index.js
- package.json
- testem.js
- tests/dummy/app/controllers/test-bed/default-value.js
- tests/dummy/app/controllers/test-bed/zany-embedded-html.js
- tests/dummy/config/environment.js
- tests/dummy/config/targets.js
- tests/helpers/start-app.js
- tests/integration/components/x-select-actions-test.js
- yarn.lock
This PR updates the CI deploy settings to fix two things:
- In my first stab at the circleci config I didn't properly setup the matrix to wait for all of the tests to run before trying to deploy
- Pagefront seems to be a dying hosting space. I switched over to using surge (which I use on my other OSS projects & love)
> Fix auto deploy on CI success / Update Ember-CLI

- .circleci/config.yml
- CNAME
- package.json
- yarn.lock
x-select has a little bit of a history with deploying the dummy app on master test success. First it was pagefront, then surge, and now its Netifly. So why the change? There's been always a struggle with surge (#207, #208, #227) and it broke once again with the latest update. So after trying to debug it I quit and will move it to Netlify. No CI config needed, they watch the repo by connecting to GitHub. 
As an awesome side effect we get review apps! 😃
> Change to netlify for deployment

- README.md
- package.json
It's been a blast maintaining emberx-select, and indeed I think we've used it on every single Ember project we've done in the last 5 years.
This changes the repository to its new home, and documents the (admittedly very loose) release process according to the [transfer docuemntation][1]
[1]: https://github.com/adopted-ember-addons/program-guidelines/blob/master/README.md
> Prepare package and docs for adoption.

- README.md
Ember X Select has been a great addon for many teams, but has not had updates to dependencies or use patterns in quite some time. From asking in Discord, the concensus for a near drop in replacement is the Ember A11Y team's Ember Select Light.
This PR updates the Readme to point out this replacement.
> Recommend Ember Select Light
